# k8s/values.yaml
environment: dev
module: success-app
service:
  type: ClusterIP
  port: 80
  targetPort: 80
image:
  repository: ghcr.io/miletocarmelo/success-app
  tag: latest
containers:
  ports:
    containerPort: 80
